variables:
  IMAGE_TAG: latest
  QUICKLISP_ADD_TO_INIT_FILE: "true"
  QUICKLISP_DIST_VERSION: latest

image: clfoundation/$LISP:$IMAGE_TAG

stages:
  - test

before_script:
  - install-quicklisp
  - cp -r . ~/quicklisp/local-projects/

.test:
  stage: test
  script: $LISP --eval "(progn (ql:quickload '(:rove)) (asdf:test-system :fcl) (quit))"

sbcl:
  extends: .test
  variables:
    LISP: sbcl

ccl:
  extends: .test
  variables:
    LISP: ccl

abcl:
  extends: .test
  variables:
    LISP: abcl

ecl:
  extends: .test
  variables:
    LISP: ecl

clasp:
  extends: .test
  variables:
    LISP: clasp
