image: daewok/lisp-devel

before_script:
    - cp -r . /usr/local/share/common-lisp/source/fcl

stages:
    - test

sbcl:
    stage: test
    script: sbcl --eval "(progn (ql:quickload '(:rove)) (asdf:test-system :fcl) (quit))"

ccl:
    stage: test
    script: ccl --eval "(progn (ql:quickload '(:rove)) (asdf:test-system :fcl) (quit))"

ecl:
    stage: test
    script: ecl --eval "(progn (ql:quickload '(:rove)) (asdf:test-system :fcl) (quit))"

abcl:
    stage: test
    script: abcl --eval "(progn (ql:quickload '(:rove)) (asdf:test-system :fcl) (quit))"
