(defpackage fcl.util
  (:use
    :common-lisp
    :fcl.u.type
    :fcl.u.list
    :fcl.u.function
    :fcl.u.symbol)
  (:export
    #:index
    #:proper-list
    #:nlist?
    #:insert-at
    #:filter
    #:mappend
    #:zip
    #:compose
    #:partial
    #:rpartial
    #:partial-at
    #:curry
    #:rcurry
    #:symbolicate))
